package token

import (
	"testing"
	"time"

	"github.com/dgrijalva/jwt-go"
	"github.com/stretchr/testify/require"

	"work-simplebank/util"
)

func TestJWTMaker(t *testing.T) {

	// I use a random string as secretKey
	maker, err := NewJWTMaker(util.RandomString(32))

	require.NoError(t, err)

	username := util.RandomOwner()
	duration := time.Minute

	issuedAt := time.Now()

	expiredAt := issuedAt.Add(duration)

	token, err := maker.CreateToken(username, duration)

	require.NoError(t, err)

	require.NotEmpty(t, token)

	payload, err := maker.VerifyToken(token)
	require.NoError(t, err)
	require.NotEmpty(t, payload)

	require.NotZero(t, payload.ID)
	require.Equal(t, username, payload.Username)

	require.WithinDuration(t, issuedAt, payload.IssuedAt, time.Second)
	require.WithinDuration(t, expiredAt, payload.ExpiredAt, time.Second)

}

func TestExpiredJWTToken(t *testing.T) {
	// I use a random string as secretKey
	maker, err := NewJWTMaker(util.RandomString(32))

	require.NoError(t, err)

	token, err := maker.CreateToken(util.RandomOwner(), -time.Minute)

	require.NoError(t, err)

	require.NotEmpty(t, token)

	// now we verify and it should return an error

	payload, err := maker.VerifyToken(token)
	require.EqualError(t, err, ErrExpiredToken.Error())
	require.Nil(t, payload)
}

func TestInvalidJWTTokenAlgNone(t *testing.T) {

	// first I create a new token with a payload generated by me...
	payload, err := NewPayload(util.RandomOwner(), time.Minute)
	require.NoError(t, err)

	jwtToken := jwt.NewWithClaims(jwt.SigningMethodNone, payload)

	maker, err := NewJWTMaker(util.RandomString(32))
	require.NoError(t, err)

	token, err := jwtToken.SignedString(jwt.UnsafeAllowNoneSignatureType)
	require.NoError(t, err)
	payload, err = maker.VerifyToken(token)
	require.EqualError(t, err, ErrInvalidToken.Error())

	require.Nil(t, payload)

}
